In [3]:
import pandas as pd

In [4]:
data=pd.read_csv('instagram_global_top_1000.csv')
data

,Country,Rank,Account,Title,Link,Category,Followers,Audience Country,Authentic engagement,Engagement avg,Scraped
0,All,1,cristiano,Cristiano Ronaldo,https://www.instagram.com/cristiano/,Sports with a ball,400100000.0,India,7800000.0,9500000.0,2022-02-07 16:50:24.798803
1,All,2,kyliejenner,Kylie ü§ç,https://www.instagram.com/kyliejenner/,Fashion|Modeling|Beauty,308800000.0,United States,6200000.0,10100000.0,2022-02-07 16:50:24.798803
2,All,3,leomessi,Leo Messi,https://www.instagram.com/leomessi/,Sports with a ball|Family,306300000.0,Argentina,4800000.0,6500000.0,2022-02-07 16:50:24.798803
3,All,4,kendalljenner,Kendall,https://www.instagram.com/kendalljenner/,Modeling|Fashion,217800000.0,United States,3400000.0,5400000.0,2022-02-07 16:50:24.798803
4,All,5,selenagomez,Selena Gomez,https://www.instagram.com/selenagomez/,Music|Lifestyle,295800000.0,United States,2700000.0,3600000.0,2022-02-07 16:50:24.798803
...,...,...,...,...,...,...,...,...,...,...,...
995,All,996,senoritasaeva,Dina Saeva,https://www.instagram.com/senoritasaeva/,Lifestyle|Music|Modeling,7700000.0,Russia,246600.0,318200.0,2022-02-07 16:50:24.798803
996,All,997,manuelneuer,Manuel Neuer,https://www.instagram.com/manuelneuer/,Sports with a ball,11500000.0,Germany,146500.0,210200.0,2022-02-07 16:50:24.798803
997,All,998,sahilkhan,India‚Äôs Youth & Fitness IC‚≠ïÔ∏èN¬Æ,https://www.instagram.com/sahilkhan/,Fitness|Gym,10100000.0,India,176500.0,239800.0,2022-02-07 16:50:24.798803
998,All,999,mohanshakti,Shakti Mohan,https://www.instagram.com/mohanshakti/,Art|Artists|Cinema|Actors/actresses,13700000.0,India,146400.0,175500.0,2022-02-07 16:50:24.798803
999,All,1000,eduincaz,Eduin Caz,https://www.instagram.com/eduincaz/,Lifestyle,6200000.0,Mexico,305600.0,391900.0,2022-02-07 16:50:24.798803

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               1000 non-null   object
 1   Rank                  1000 non-null   int64
 2   Account               1000 non-null   object
 3   Title                 983 non-null    object
 4   Link                  1000 non-null   object
 5   Category              909 non-null    object
 6   Followers             1000 non-null   float64
 7   Audience Country      993 non-null    object
 8   Authentic engagement  1000 non-null   float64
 9   Engagement avg        1000 non-null   float64
 10  Scraped               1000 non-null   object
dtypes: float64(3), int64(1), object(7)
memory usage: 86.1+ KB

In [6]:
a=data.head(20)
a

,Country,Rank,Account,Title,Link,Category,Followers,Audience Country,Authentic engagement,Engagement avg,Scraped
0,All,1,cristiano,Cristiano Ronaldo,https://www.instagram.com/cristiano/,Sports with a ball,400100000.0,India,7800000.0,9500000.0,2022-02-07 16:50:24.798803
1,All,2,kyliejenner,Kylie ü§ç,https://www.instagram.com/kyliejenner/,Fashion|Modeling|Beauty,308800000.0,United States,6200000.0,10100000.0,2022-02-07 16:50:24.798803
2,All,3,leomessi,Leo Messi,https://www.instagram.com/leomessi/,Sports with a ball|Family,306300000.0,Argentina,4800000.0,6500000.0,2022-02-07 16:50:24.798803
3,All,4,kendalljenner,Kendall,https://www.instagram.com/kendalljenner/,Modeling|Fashion,217800000.0,United States,3400000.0,5400000.0,2022-02-07 16:50:24.798803
4,All,5,selenagomez,Selena Gomez,https://www.instagram.com/selenagomez/,Music|Lifestyle,295800000.0,United States,2700000.0,3600000.0,2022-02-07 16:50:24.798803
5,All,6,zendaya,Zendaya,https://www.instagram.com/zendaya/,Cinema|Actors/actresses|Fashion,127800000.0,United States,5800000.0,7800000.0,2022-02-07 16:50:24.798803
6,All,7,kimkardashian,Kim Kardashian West,https://www.instagram.com/kimkardashian/,Fashion|Beauty,284900000.0,United States,2200000.0,3300000.0,2022-02-07 16:50:24.798803
7,All,8,beyonce,BeyonceÃÅ,https://www.instagram.com/beyonce/,Music|Fashion,237200000.0,United States,2500000.0,3600000.0,2022-02-07 16:50:24.798803
8,All,9,arianagrande,Ariana Grande,https://www.instagram.com/arianagrande/,Music,294100000.0,United States,1700000.0,2400000.0,2022-02-07 16:50:24.798803
9,All,10,billieeilish,BILLIE EILISH,https://www.instagram.com/billieeilish/,Music,100000000.0,United States,5300000.0,7000000.0,2022-02-07 16:50:24.798803
10,All,11,neymarjr,NJ üáßüá∑,https://www.instagram.com/neymarjr/,Sports with a ball,169800000.0,Brazil,2800000.0,4000000.0,2022-02-07 16:50:24.798803
11,All,12,lalalalisa_m,LISA,https://www.instagram.com/lalalalisa_m/,Music,73100000.0,Indonesia,7500000.0,8600000.0,2022-02-07 16:50:24.798803
12,All,13,jennierubyjane,J,https://www.instagram.com/jennierubyjane/,Music,62300000.0,Indonesia,6400000.0,7600000.0,2022-02-07 16:50:24.798803
13,All,14,tomholland2013,Tom Holland,https://www.instagram.com/tomholland2013/,Cinema|Actors/actresses,60900000.0,United States,5900000.0,7200000.0,2022-02-07 16:50:24.798803
14,All,15,virat.kohli,Virat Kohli,https://www.instagram.com/virat.kohli/,Sports with a ball,182600000.0,India,2100000.0,2400000.0,2022-02-07 16:50:24.798803
15,All,16,abcdefghi__lmnopqrstuvwxyz,Jungkook,https://www.instagram.com/abcdefghi__lmnopqrst...,NaN,32100000.0,United States,13400000.0,13400000.0,2022-02-07 16:50:24.798803
16,All,17,khaby00,Khaby Lame,https://www.instagram.com/khaby00/,NaN,69200000.0,Iran,4000000.0,6100000.0,2022-02-07 16:50:24.798803
17,All,18,khloekardashian,KhloeÃÅ Kardashian,https://www.instagram.com/khloekardashian/,Clothing|Outfits|Lifestyle,219400000.0,United States,1500000.0,1900000.0,2022-02-07 16:50:24.798803
18,All,19,sooyaaa__,JISOOü§ç,https://www.instagram.com/sooyaaa__/,Music|Beauty,56100000.0,Indonesia,6300000.0,7200000.0,2022-02-07 16:50:24.798803
19,All,20,justinbieber,Justin Bieber,https://www.instagram.com/justinbieber/,Music,219800000.0,India,1200000.0,1800000.0,2022-02-07 16:50:24.798803

# 2a.How many influencers in the top 20 are into sports?

In [18]:
#The number of influencers in the top 20 that are into Sports
b=a[(a['Category']=='Sports with a ball')]
b

,Country,Rank,Account,Title,Link,Category,Followers,Audience Country,Authentic engagement,Engagement avg,Scraped
0,All,1,cristiano,Cristiano Ronaldo,https://www.instagram.com/cristiano/,Sports with a ball,400100000.0,India,7800000.0,9500000.0,2022-02-07 16:50:24.798803
10,All,11,neymarjr,NJ üáßüá∑,https://www.instagram.com/neymarjr/,Sports with a ball,169800000.0,Brazil,2800000.0,4000000.0,2022-02-07 16:50:24.798803
14,All,15,virat.kohli,Virat Kohli,https://www.instagram.com/virat.kohli/,Sports with a ball,182600000.0,India,2100000.0,2400000.0,2022-02-07 16:50:24.798803

# 2b.How many musicians were in the top 100, which countries were their audience from and how many followers did they have?

In [19]:
c=data.head(100)
pd.set_option('display.max_rows',100)
c

,Country,Rank,Account,Title,Link,Category,Followers,Audience Country,Authentic engagement,Engagement avg,Scraped
0,All,1,cristiano,Cristiano Ronaldo,https://www.instagram.com/cristiano/,Sports with a ball,400100000.0,India,7800000.0,9500000.0,2022-02-07 16:50:24.798803
1,All,2,kyliejenner,Kylie ü§ç,https://www.instagram.com/kyliejenner/,Fashion|Modeling|Beauty,308800000.0,United States,6200000.0,10100000.0,2022-02-07 16:50:24.798803
2,All,3,leomessi,Leo Messi,https://www.instagram.com/leomessi/,Sports with a ball|Family,306300000.0,Argentina,4800000.0,6500000.0,2022-02-07 16:50:24.798803
3,All,4,kendalljenner,Kendall,https://www.instagram.com/kendalljenner/,Modeling|Fashion,217800000.0,United States,3400000.0,5400000.0,2022-02-07 16:50:24.798803
4,All,5,selenagomez,Selena Gomez,https://www.instagram.com/selenagomez/,Music|Lifestyle,295800000.0,United States,2700000.0,3600000.0,2022-02-07 16:50:24.798803
5,All,6,zendaya,Zendaya,https://www.instagram.com/zendaya/,Cinema|Actors/actresses|Fashion,127800000.0,United States,5800000.0,7800000.0,2022-02-07 16:50:24.798803
6,All,7,kimkardashian,Kim Kardashian West,https://www.instagram.com/kimkardashian/,Fashion|Beauty,284900000.0,United States,2200000.0,3300000.0,2022-02-07 16:50:24.798803
7,All,8,beyonce,BeyonceÃÅ,https://www.instagram.com/beyonce/,Music|Fashion,237200000.0,United States,2500000.0,3600000.0,2022-02-07 16:50:24.798803
8,All,9,arianagrande,Ariana Grande,https://www.instagram.com/arianagrande/,Music,294100000.0,United States,1700000.0,2400000.0,2022-02-07 16:50:24.798803
9,All,10,billieeilish,BILLIE EILISH,https://www.instagram.com/billieeilish/,Music,100000000.0,United States,5300000.0,7000000.0,2022-02-07 16:50:24.798803
10,All,11,neymarjr,NJ üáßüá∑,https://www.instagram.com/neymarjr/,Sports with a ball,169800000.0,Brazil,2800000.0,4000000.0,2022-02-07 16:50:24.798803
11,All,12,lalalalisa_m,LISA,https://www.instagram.com/lalalalisa_m/,Music,73100000.0,Indonesia,7500000.0,8600000.0,2022-02-07 16:50:24.798803
12,All,13,jennierubyjane,J,https://www.instagram.com/jennierubyjane/,Music,62300000.0,Indonesia,6400000.0,7600000.0,2022-02-07 16:50:24.798803
13,All,14,tomholland2013,Tom Holland,https://www.instagram.com/tomholland2013/,Cinema|Actors/actresses,60900000.0,United States,5900000.0,7200000.0,2022-02-07 16:50:24.798803
14,All,15,virat.kohli,Virat Kohli,https://www.instagram.com/virat.kohli/,Sports with a ball,182600000.0,India,2100000.0,2400000.0,2022-02-07 16:50:24.798803
15,All,16,abcdefghi__lmnopqrstuvwxyz,Jungkook,https://www.instagram.com/abcdefghi__lmnopqrst...,NaN,32100000.0,United States,13400000.0,13400000.0,2022-02-07 16:50:24.798803
16,All,17,khaby00,Khaby Lame,https://www.instagram.com/khaby00/,NaN,69200000.0,Iran,4000000.0,6100000.0,2022-02-07 16:50:24.798803
17,All,18,khloekardashian,KhloeÃÅ Kardashian,https://www.instagram.com/khloekardashian/,Clothing|Outfits|Lifestyle,219400000.0,United States,1500000.0,1900000.0,2022-02-07 16:50:24.798803
18,All,19,sooyaaa__,JISOOü§ç,https://www.instagram.com/sooyaaa__/,Music|Beauty,56100000.0,Indonesia,6300000.0,7200000.0,2022-02-07 16:50:24.798803
19,All,20,justinbieber,Justin Bieber,https://www.instagram.com/justinbieber/,Music,219800000.0,India,1200000.0,1800000.0,2022-02-07 16:50:24.798803
20,All,21,thv,V,https://www.instagram.com/thv/,NaN,34100000.0,NaN,10400000.0,10400000.0,2022-02-07 16:50:24.798803
21,All,22,roses_are_rosie,ROSEÃÅ,https://www.instagram.com/roses_are_rosie/,Music,55100000.0,Indonesia,5500000.0,6400000.0,2022-02-07 16:50:24.798803
22,All,23,badgalriri,badgalriri,https://www.instagram.com/badgalriri/,Music|Beauty,120900000.0,United States,1700000.0,2800000.0,2022-02-07 16:50:24.798803
23,All,24,nickiminaj,Barbie,https://www.instagram.com/nickiminaj/,Music,174000000.0,United States,1200000.0,1900000.0,2022-02-07 16:50:24.798803
24,All,25,iamcardib,Cardi B,https://www.instagram.com/iamcardib/,Music|Fashion,123100000.0,United States,1800000.0,2600000.0,2022-02-07 16:50:24.798803
25,All,26,jin,Jin of BTS,https://www.instagram.com/jin/,NaN,28400000.0,United States,11100000.0,11100000.0,2022-02-07 16:50:24.798803
26,All,27,agustd,SUGA of BTS ÎØºÏú§Í∏∞,https://www.instagram.com/agustd/,NaN,27900000.0,NaN,10600000.0,10600000.0,2022-02-07 16:50:24.798803
27,All,28,therock,therock,https://www.instagram.com/therock/,Cinema|Actors/actresses|Fitness|Gym,295800000.0,India,741000.0,994800.0,2022-02-07 16:50:24.798803
28,All,29,instagram,Instagram,https://www.instagram.com/instagram/,Photography,469600000.0,India,490400.0,608100.0,2022-02-07 16:50:24.798803
29,All,30,zayn,Zayn Malik,https://www.instagram.com/zayn/,Music,44500000.0,India,3800000.0,6000000.0,2022-02-07 16:50:24.798803
30,All,31,champagnepapi,champagnepapi,https://www.instagram.com/champagnepapi/,Music,102600000.0,United States,1500000.0,2500000.0,2022-02-07 16:50:24.798803
31,All,32,rkive,RM,https://www.instagram.com/rkive/,NaN,28000000.0,NaN,8900000.0,8900000.0,2022-02-07 16:50:24.798803
32,All,33,kourtneykardash,Kourtney ‚ù§Ô∏è,https://www.instagram.com/kourtneykardash/,Lifestyle,162200000.0,United States,1100000.0,1500000.0,2022-02-07 16:50:24.798803
33,All,34,uarmyhope,jhope,https://www.instagram.com/uarmyhope/,NaN,28500000.0,United States,8500000.0,8500000.0,2022-02-07 16:50:24.798803
34,All,35,badbunnypr,NaN,https://www.instagram.com/badbunnypr/,Music,37800000.0,United States,4100000.0,6500000.0,2022-02-07 16:50:24.798803
35,All,36,katrinakaif,Katrina Kaif,https://www.instagram.com/katrinakaif/,Beauty,61600000.0,India,3300000.0,3800000.0,2022-02-07 16:50:24.798803
36,All,37,adele,Adele,https://www.instagram.com/adele/,Music,49100000.0,United States,2800000.0,3900000.0,2022-02-07 16:50:24.798803
37,All,38,harrystyles,NaN,https://www.instagram.com/harrystyles/,Music|Fashion,43000000.0,Brazil,3000000.0,4000000.0,2022-02-07 16:50:24.798803
38,All,39,kingjames,üëë,https://www.instagram.com/kingjames/,Sports with a ball,111400000.0,United States,884300.0,1500000.0,2022-02-07 16:50:24.798803
39,All,40,jlo,Jennifer Lopez,https://www.instagram.com/jlo/,Music|Cinema|Actors/actresses,194900000.0,United States,679200.0,856000.0,2022-02-07 16:50:24.798803
40,All,41,k.mbappe,Kylian MbappeÃÅ,https://www.instagram.com/k.mbappe/,Sports with a ball,65800000.0,France,1700000.0,2400000.0,2022-02-07 16:50:24.798803
41,All,42,karolg,KAROL G,https://www.instagram.com/karolg/,Music,47300000.0,Mexico,2600000.0,3200000.0,2022-02-07 16:50:24.798803
42,All,43,gigihadid,Gigi Hadid,https://www.instagram.com/gigihadid/,Modeling|Lifestyle,72300000.0,United States,1300000.0,1900000.0,2022-02-07 16:50:24.798803
43,All,44,anushkasharma,AnushkaSharma1588,https://www.instagram.com/anushkasharma/,Cinema|Actors/actresses,56900000.0,India,2200000.0,2400000.0,2022-02-07 16:50:24.798803
44,All,45,narendramodi,Narendra Modi,https://www.instagram.com/narendramodi/,Finance|Economics|Business|Careers,65300000.0,India,1800000.0,2000000.0,2022-02-07 16:50:24.798803
45,All,46,eunwo.o_c,Ï∞®ÏùÄÏö∞,https://www.instagram.com/eunwo.o_c/,Music|Lifestyle,26500000.0,Indonesia,3700000.0,4600000.0,2022-02-07 16:50:24.798803
46,All,47,dualipa,DUA LIPA,https://www.instagram.com/dualipa/,Music,78700000.0,Mexico,1200000.0,1400000.0,2022-02-07 16:50:24.798803
47,All,48,charlidamelio,cd,https://www.instagram.com/charlidamelio/,Lifestyle|Shows,47100000.0,United States,1900000.0,2400000.0,2022-02-07 16:50:24.798803
48,All,49,ester_exposito,Ester üåô,https://www.instagram.com/ester_exposito/,Cinema|Actors/actresses,29000000.0,Russia,2500000.0,3700000.0,2022-02-07 16:50:24.798803
49,All,50,mileycyrus,Miley Cyrus,https://www.instagram.com/mileycyrus/,Music,160200000.0,United States,501600.0,667900.0,2022-02-07 16:50:24.798803
50,All,51,georginagio,Georgina RodriÃÅguez,https://www.instagram.com/georginagio/,Lifestyle|Fashion|Clothing|Outfits,33400000.0,India,2200000.0,3200000.0,2022-02-07 16:50:24.798803
51,All,52,actorleeminho,·Ñã·Öµ·ÑÜ·Öµ·Ü´·Ñí·Ö© leeminho,https://www.instagram.com/actorleeminho/,Cinema|Actors/actresses,28200000.0,Indonesia,2900000.0,3800000.0,2022-02-07 16:50:24.798803
52,All,53,gal_gadot,Gal Gadot,https://www.instagram.com/gal_gadot/,Cinema|Actors/actresses,73600000.0,United States,1100000.0,1400000.0,2022-02-07 16:50:24.798803
53,All,54,fcbarcelona,FC Barcelona,https://www.instagram.com/fcbarcelona/,Sports with a ball,105100000.0,Indonesia,621000.0,950400.0,2022-02-07 16:50:24.798803
54,All,55,akshaykumar,Akshay Kumar,https://www.instagram.com/akshaykumar/,Cinema|Actors/actresses,59500000.0,India,1400000.0,1600000.0,2022-02-07 16:50:24.798803
55,All,56,shawnmendes,Shawn Mendes,https://www.instagram.com/shawnmendes/,Music,66500000.0,Brazil,923900.0,1400000.0,2022-02-07 16:50:24.798803
56,All,57,milliebobbybrown,Millie Bobby Brown,https://www.instagram.com/milliebobbybrown/,Cinema|Actors/actresses,47500000.0,Brazil,1400000.0,1700000.0,2022-02-07 16:50:24.798803
57,All,58,chrishemsworth,Chris Hemsworth,https://www.instagram.com/chrishemsworth/,Cinema|Actors/actresses,53500000.0,India,1200000.0,1500000.0,2022-02-07 16:50:24.798803
58,All,59,dlwlrma,·Ñã·Öµ·Ñå·Öµ·ÑÄ·Ö≥·Ü∑ IU,https://www.instagram.com/dlwlrma/,Art|Artists,25000000.0,South Korea,2700000.0,3200000.0,2022-02-07 16:50:24.798803
59,All,60,oliviarodrigo,Olivia Rodrigo,https://www.instagram.com/oliviarodrigo/,Music|Cinema|Actors/actresses,21600000.0,India,2900000.0,3600000.0,2022-02-07 16:50:24.798803
60,All,61,mosalah,Mohamed Salah,https://www.instagram.com/mosalah/,Sports with a ball,47900000.0,Egypt,1100000.0,1600000.0,2022-02-07 16:50:24.798803
61,All,62,rashmika_mandanna,Rashmika Mandanna,https://www.instagram.com/rashmika_mandanna/,Beauty|Art|Artists|Cinema|Actors/actresses,28600000.0,India,2300000.0,2700000.0,2022-02-07 16:50:24.798803
62,All,63,lelepons,Lele Pons,https://www.instagram.com/lelepons/,Music,47300000.0,Mexico,1000000.0,1600000.0,2022-02-07 16:50:24.798803
63,All,64,ursulolita,UÃÅrsula CorberoÃÅ üê£,https://www.instagram.com/ursulolita/,Cinema|Actors/actresses|Modeling,24900000.0,Brazil,2000000.0,3000000.0,2022-02-07 16:50:24.798803
64,All,65,priyankachopra,Priyanka,https://www.instagram.com/priyankachopra/,Cinema|Actors/actresses,74000000.0,India,817700.0,997000.0,2022-02-07 16:50:24.798803
65,All,66,lilireinhart,Lili Reinhart,https://www.instagram.com/lilireinhart/,Cinema|Actors/actresses,29300000.0,Brazil,1700000.0,2500000.0,2022-02-07 16:50:24.798803
66,All,67,handemiyy,Hande ErcÃßel,https://www.instagram.com/handemiyy/,Cinema|Actors/actresses,26700000.0,Turkey,2000000.0,2700000.0,2022-02-07 16:50:24.798803
67,All,68,ddlovato,Demi Lovato,https://www.instagram.com/ddlovato/,Music,125800000.0,United States,439400.0,564800.0,2022-02-07 16:50:24.798803
68,All,69,blackpinkofficial,BLŒõ∆ÜKPI–òK,https://www.instagram.com/blackpinkofficial/,Music,45200000.0,Indonesia,1200000.0,1500000.0,2022-02-07 16:50:24.798803
69,All,70,whinderssonnunes,Whindersson Nunes,https://www.instagram.com/whinderssonnunes/,Humor|Fun|Happiness,57100000.0,Brazil,781800.0,1200000.0,2022-02-07 16:50:24.798803
70,All,71,shraddhakapoor,Shraddha ‚ú∂,https://www.instagram.com/shraddhakapoor/,Cinema|Actors/actresses,68900000.0,India,797300.0,921500.0,2022-02-07 16:50:24.798803
71,All,72,meganfox,Megan Fox,https://www.instagram.com/meganfox/,Cinema|Actors/actresses,18800000.0,United States,2000000.0,3300000.0,2022-02-07 16:50:24.798803
72,All,73,haileybieber,Hailey Rhode Baldwin Bieber,https://www.instagram.com/haileybieber/,Lifestyle|Modeling,41000000.0,United States,1100000.0,1500000.0,2022-02-07 16:50:24.798803
73,All,74,bn_sj2013,·Ñá·Ö°·Ü®·Ñâ·Ö•·Ñå·ÖÆ·Ü´,https://www.instagram.com/bn_sj2013/,Cinema|Actors/actresses|Modeling|Lifestyle,20900000.0,Indonesia,2500000.0,3000000.0,2022-02-07 16:50:24.798803
74,All,75,kimberly.loaiza,KIM LOAIZA üñ§,https://www.instagram.com/kimberly.loaiza/,Clothing|Outfits|Lifestyle,33400000.0,Mexico,1500000.0,1900000.0,2022-02-07 16:50:24.798803
75,All,76,real__pcy,EXO_CY,https://www.instagram.com/real__pcy/,Music,23600000.0,Indonesia,2200000.0,2700000.0,2022-02-07 16:50:24.798803
76,All,77,katyperry,KATY PERRY,https://www.instagram.com/katyperry/,Music,151900000.0,Brazil,319500.0,408100.0,2022-02-07 16:50:24.798803
77,All,78,davidbeckham,David Beckham,https://www.instagram.com/davidbeckham/,Family|Sports with a ball,71100000.0,India,653200.0,866300.0,2022-02-07 16:50:24.798803
78,All,79,camila_cabello,camila,https://www.instagram.com/camila_cabello/,Music,60000000.0,Brazil,747600.0,1000000.0,2022-02-07 16:50:24.798803
79,All,80,paulpogba,Paul Labile Pogba,https://www.instagram.com/paulpogba/,Sports with a ball,51500000.0,Brazil,623400.0,1100000.0,2022-02-07 16:50:24.798803
80,All,81,aliaabhatt,Gangubai ü§çüôè,https://www.instagram.com/aliaabhatt/,Cinema|Actors/actresses,58900000.0,India,781800.0,970900.0,2022-02-07 16:50:24.798803
81,All,82,dojacat,Doja Cat,https://www.instagram.com/dojacat/,Music,19700000.0,United States,2100000.0,2900000.0,2022-02-07 16:50:24.798803
82,All,83,iamsrk,Shah Rukh Khan,https://www.instagram.com/iamsrk/,Cinema|Actors/actresses,28000000.0,India,1600000.0,2000000.0,2022-02-07 16:50:24.798803
83,All,84,realmadrid,Real Madrid C.F.,https://www.instagram.com/realmadrid/,Sports with a ball,109800000.0,Spain,364000.0,505000.0,2022-02-07 16:50:24.798803
84,All,85,jongsuk0206,Ïù¥Ï¢ÖÏÑù,https://www.instagram.com/jongsuk0206/,Cinema|Actors/actresses,21800000.0,Indonesia,1900000.0,2500000.0,2022-02-07 16:50:24.798803
85,All,86,miakhalifa,Mia K.,https://www.instagram.com/miakhalifa/,Fitness|Gym|Lifestyle,27000000.0,India,1300000.0,2000000.0,2022-02-07 16:50:24.798803
86,All,87,nasa,NASA,https://www.instagram.com/nasa/,Science|Photography,73900000.0,India,637700.0,738600.0,2022-02-07 16:50:24.798803
87,All,88,bellahadid,Bella ü¶ã,https://www.instagram.com/bellahadid/,Modeling,49100000.0,United States,685300.0,1100000.0,2022-02-07 16:50:24.798803
88,All,89,oohsehun,SEHUN,https://www.instagram.com/oohsehun/,Music,22800000.0,Indonesia,1900000.0,2400000.0,2022-02-07 16:50:24.798803
89,All,90,niallhoran,Niall Horan,https://www.instagram.com/niallhoran/,Music,29200000.0,United States,1300000.0,1800000.0,2022-02-07 16:50:24.798803
90,All,91,hoooooyeony,Hoyeon,https://www.instagram.com/hoooooyeony/,Lifestyle,23500000.0,South Korea,1700000.0,2200000.0,2022-02-07 16:50:24.798803
91,All,92,addisonraee,Addison Rae,https://www.instagram.com/addisonraee/,Beauty,40300000.0,United States,826000.0,1300000.0,2022-02-07 16:50:24.798803
92,All,93,beingsalmankhan,Salman Khan,https://www.instagram.com/beingsalmankhan/,Cinema|Actors/actresses|Art|Artists,49500000.0,India,818300.0,1000000.0,2022-02-07 16:50:24.798803
93,All,94,twicetagram,TWICE,https://www.instagram.com/twicetagram/,Music|Modeling,23500000.0,Indonesia,1700000.0,2100000.0,2022-02-07 16:50:24.798803
94,All,95,emmawatson,Emma Watson,https://www.instagram.com/emmawatson/,Literature|Journalism|Cinema|Actors/actresses|...,65700000.0,United States,549600.0,753600.0,2022-02-07 16:50:24.798803
95,All,96,zacefron,Zac Efron,https://www.instagram.com/zacefron/,Cinema|Actors/actresses,51400000.0,United States,665400.0,961700.0,2022-02-07 16:50:24.798803
96,All,97,nike,Nike,https://www.instagram.com/nike/,Fitness|Gym|Shopping|Retail|Clothing|Outfits,199000000.0,United States,200500.0,257800.0,2022-02-07 16:50:24.798803
97,All,98,madelame,Madelaine Petsch,https://www.instagram.com/madelame/,Cinema|Actors/actresses,25400000.0,Russia,1400000.0,1900000.0,2022-02-07 16:50:24.798803
98,All,99,virginia,Virginia Fonseca Costa,https://www.instagram.com/virginia/,Shows|Lifestyle,33300000.0,Brazil,923300.0,1400000.0,2022-02-07 16:50:24.798803
99,All,100,jenniferaniston,Jennifer Aniston,https://www.instagram.com/jenniferaniston/,Cinema|Actors/actresses,39600000.0,Brazil,826400.0,1200000.0,2022-02-07 16:50:24.798803

In [20]:
d=c[['Category','Followers','Audience Country']]
d

,Category,Followers,Audience Country
0,Sports with a ball,400100000.0,India
1,Fashion|Modeling|Beauty,308800000.0,United States
2,Sports with a ball|Family,306300000.0,Argentina
3,Modeling|Fashion,217800000.0,United States
4,Music|Lifestyle,295800000.0,United States
5,Cinema|Actors/actresses|Fashion,127800000.0,United States
6,Fashion|Beauty,284900000.0,United States
7,Music|Fashion,237200000.0,United States
8,Music,294100000.0,United States
9,Music,100000000.0,United States
10,Sports with a ball,169800000.0,Brazil
11,Music,73100000.0,Indonesia
12,Music,62300000.0,Indonesia
13,Cinema|Actors/actresses,60900000.0,United States
14,Sports with a ball,182600000.0,India
15,NaN,32100000.0,United States
16,NaN,69200000.0,Iran
17,Clothing|Outfits|Lifestyle,219400000.0,United States
18,Music|Beauty,56100000.0,Indonesia
19,Music,219800000.0,India
20,NaN,34100000.0,NaN
21,Music,55100000.0,Indonesia
22,Music|Beauty,120900000.0,United States
23,Music,174000000.0,United States
24,Music|Fashion,123100000.0,United States
25,NaN,28400000.0,United States
26,NaN,27900000.0,NaN
27,Cinema|Actors/actresses|Fitness|Gym,295800000.0,India
28,Photography,469600000.0,India
29,Music,44500000.0,India
30,Music,102600000.0,United States
31,NaN,28000000.0,NaN
32,Lifestyle,162200000.0,United States
33,NaN,28500000.0,United States
34,Music,37800000.0,United States
35,Beauty,61600000.0,India
36,Music,49100000.0,United States
37,Music|Fashion,43000000.0,Brazil
38,Sports with a ball,111400000.0,United States
39,Music|Cinema|Actors/actresses,194900000.0,United States
40,Sports with a ball,65800000.0,France
41,Music,47300000.0,Mexico
42,Modeling|Lifestyle,72300000.0,United States
43,Cinema|Actors/actresses,56900000.0,India
44,Finance|Economics|Business|Careers,65300000.0,India
45,Music|Lifestyle,26500000.0,Indonesia
46,Music,78700000.0,Mexico
47,Lifestyle|Shows,47100000.0,United States
48,Cinema|Actors/actresses,29000000.0,Russia
49,Music,160200000.0,United States
50,Lifestyle|Fashion|Clothing|Outfits,33400000.0,India
51,Cinema|Actors/actresses,28200000.0,Indonesia
52,Cinema|Actors/actresses,73600000.0,United States
53,Sports with a ball,105100000.0,Indonesia
54,Cinema|Actors/actresses,59500000.0,India
55,Music,66500000.0,Brazil
56,Cinema|Actors/actresses,47500000.0,Brazil
57,Cinema|Actors/actresses,53500000.0,India
58,Art|Artists,25000000.0,South Korea
59,Music|Cinema|Actors/actresses,21600000.0,India
60,Sports with a ball,47900000.0,Egypt
61,Beauty|Art|Artists|Cinema|Actors/actresses,28600000.0,India
62,Music,47300000.0,Mexico
63,Cinema|Actors/actresses|Modeling,24900000.0,Brazil
64,Cinema|Actors/actresses,74000000.0,India
65,Cinema|Actors/actresses,29300000.0,Brazil
66,Cinema|Actors/actresses,26700000.0,Turkey
67,Music,125800000.0,United States
68,Music,45200000.0,Indonesia
69,Humor|Fun|Happiness,57100000.0,Brazil
70,Cinema|Actors/actresses,68900000.0,India
71,Cinema|Actors/actresses,18800000.0,United States
72,Lifestyle|Modeling,41000000.0,United States
73,Cinema|Actors/actresses|Modeling|Lifestyle,20900000.0,Indonesia
74,Clothing|Outfits|Lifestyle,33400000.0,Mexico
75,Music,23600000.0,Indonesia
76,Music,151900000.0,Brazil
77,Family|Sports with a ball,71100000.0,India
78,Music,60000000.0,Brazil
79,Sports with a ball,51500000.0,Brazil
80,Cinema|Actors/actresses,58900000.0,India
81,Music,19700000.0,United States
82,Cinema|Actors/actresses,28000000.0,India
83,Sports with a ball,109800000.0,Spain
84,Cinema|Actors/actresses,21800000.0,Indonesia
85,Fitness|Gym|Lifestyle,27000000.0,India
86,Science|Photography,73900000.0,India
87,Modeling,49100000.0,United States
88,Music,22800000.0,Indonesia
89,Music,29200000.0,United States
90,Lifestyle,23500000.0,South Korea
91,Beauty,40300000.0,United States
92,Cinema|Actors/actresses|Art|Artists,49500000.0,India
93,Music|Modeling,23500000.0,Indonesia
94,Literature|Journalism|Cinema|Actors/actresses|...,65700000.0,United States
95,Cinema|Actors/actresses,51400000.0,United States
96,Fitness|Gym|Shopping|Retail|Clothing|Outfits,199000000.0,United States
97,Cinema|Actors/actresses,25400000.0,Russia
98,Shows|Lifestyle,33300000.0,Brazil
99,Cinema|Actors/actresses,39600000.0,Brazil

In [22]:
#The number of musicians in the top 100 the country of their audience and the followers
m=d[(d['Category']=='Music')]
m

   Category    Followers Audience Country
8     Music  294100000.0    United States
9     Music  100000000.0    United States
11    Music   73100000.0        Indonesia
12    Music   62300000.0        Indonesia
19    Music  219800000.0            India
21    Music   55100000.0        Indonesia
23    Music  174000000.0    United States
29    Music   44500000.0            India
30    Music  102600000.0    United States
34    Music   37800000.0    United States
36    Music   49100000.0    United States
41    Music   47300000.0           Mexico
46    Music   78700000.0           Mexico
49    Music  160200000.0    United States
55    Music   66500000.0           Brazil
62    Music   47300000.0           Mexico
67    Music  125800000.0    United States
68    Music   45200000.0        Indonesia
75    Music   23600000.0        Indonesia
76    Music  151900000.0           Brazil
78    Music   60000000.0           Brazil
81    Music   19700000.0    United States
88    Music   22800000.0        Indonesia
89    Music   29200000.0    United States

In [23]:
m.shape

(24, 3)

In [ ]:
data.info()

In [24]:
df=data[['Audience Country','Followers','Engagement avg','Title']]
df

,Audience Country,Followers,Engagement avg,Title
0,India,400100000.0,9500000.0,Cristiano Ronaldo
1,United States,308800000.0,10100000.0,Kylie ü§ç
2,Argentina,306300000.0,6500000.0,Leo Messi
3,United States,217800000.0,5400000.0,Kendall
4,United States,295800000.0,3600000.0,Selena Gomez
...,...,...,...,...
995,Russia,7700000.0,318200.0,Dina Saeva
996,Germany,11500000.0,210200.0,Manuel Neuer
997,India,10100000.0,239800.0,India‚Äôs Youth & Fitness IC‚≠ïÔ∏èN¬Æ
998,India,13700000.0,175500.0,Shakti Mohan
999,Mexico,6200000.0,391900.0,Eduin Caz

# 2c.Find out how many influencers had Indian audiences, their profession, their number of followers and their average engagement

In [25]:
#The number of Indian audiences, their profession, their number of followers and their average engagement
dt=df[(df['Audience Country']=='India')]
pd.set_option('display.max_rows',143)
dt

,Audience Country,Followers,Engagement avg,Title
0,India,400100000.0,9500000.0,Cristiano Ronaldo
14,India,182600000.0,2400000.0,Virat Kohli
19,India,219800000.0,1800000.0,Justin Bieber
27,India,295800000.0,994800.0,therock
28,India,469600000.0,608100.0,Instagram
29,India,44500000.0,6000000.0,Zayn Malik
35,India,61600000.0,3800000.0,Katrina Kaif
43,India,56900000.0,2400000.0,AnushkaSharma1588
44,India,65300000.0,2000000.0,Narendra Modi
50,India,33400000.0,3200000.0,Georgina RodriÃÅguez
54,India,59500000.0,1600000.0,Akshay Kumar
57,India,53500000.0,1500000.0,Chris Hemsworth
59,India,21600000.0,3600000.0,Olivia Rodrigo
61,India,28600000.0,2700000.0,Rashmika Mandanna
64,India,74000000.0,997000.0,Priyanka
70,India,68900000.0,921500.0,Shraddha ‚ú∂
77,India,71100000.0,866300.0,David Beckham
80,India,58900000.0,970900.0,Gangubai ü§çüôè
82,India,28000000.0,2000000.0,Shah Rukh Khan
85,India,27000000.0,2000000.0,Mia K.
86,India,73900000.0,738600.0,NASA
92,India,49500000.0,1000000.0,Salman Khan
106,India,37800000.0,1100000.0,Nora Fatehi
109,India,67600000.0,595900.0,Neha Kakkar (Mrs. Singh)
117,India,71600000.0,500700.0,Shakira
120,India,39900000.0,862400.0,VarunDhawan
124,India,39300000.0,852000.0,Sara Ali Khan
125,India,40000000.0,833600.0,Jannat Zubair Rahmani
126,India,64200000.0,516300.0,Deepika Padukone
130,India,16400000.0,2000000.0,Allu Arjun
133,India,41300000.0,761600.0,Hrithik Roshan
140,India,22500000.0,1300000.0,Rohit Sharma
156,India,23400000.0,1100000.0,KARTIK AARYAN
158,India,45900000.0,534300.0,Kriti
159,India,33100000.0,731200.0,Shahid Kapoor
160,India,48500000.0,495900.0,disha patani (paatni) ü¶ã
165,India,14600000.0,1600000.0,Vijay Deverakonda
176,India,21600000.0,1000000.0,Samantha
180,India,14500000.0,1500000.0,ùë®ùíãùíÜùíö ùëµùíÇùíàùíÇùíì
183,India,11700000.0,1800000.0,Johnny Depp
187,India,21700000.0,952300.0,KIARA
196,India,57900000.0,341400.0,Jacqueline Fernandez
198,India,20200000.0,967600.0,Hardik Himanshu Pandya
215,India,50500000.0,344700.0,Sunny Leone
220,India,14100000.0,1200000.0,Bhuvan Bam
221,India,32200000.0,531100.0,Anushka Sen
228,India,19600000.0,852300.0,ùêëùê®ùê°ùê¢ùê≠ ùêôùê¢ùêßùê£ùêÆùê´ùê§ùêû ~ ùê´ùêûùêöùêúùê≠ùê¢ùê®ùêßùêõùê®ùê¢ üí´
231,India,12500000.0,1300000.0,Ashish Chanchlani
236,India,17400000.0,917400.0,Pooja Hegde
240,India,12800000.0,1200000.0,Vicky Kaushal
250,India,33400000.0,456300.0,Tiger Shroff
252,India,28800000.0,525000.0,Avneet Kaur Official
258,India,27100000.0,538700.0,NaN
260,India,11100000.0,1400000.0,Shehnaaz Gill
262,India,18200000.0,792000.0,Sidharth Malhotra
266,India,15400000.0,927700.0,Janhvi Kapoor
277,India,29300000.0,461800.0,marshmello
282,India,45500000.0,296400.0,URVASHI RAUTELA üáÆüá≥
286,India,20800000.0,635800.0,Kajal A Kitchlu
287,India,32900000.0,398100.0,Sachin Tendulkar
293,India,35500000.0,350900.0,Marvel Studios
304,India,38500000.0,312300.0,Kapil Sharma
340,India,24900000.0,412800.0,Riyaz Aly
353,India,11600000.0,825000.0,KL Rahulüëë
355,India,15400000.0,619400.0,Awez Darbar
357,India,29800000.0,318700.0,Amitabh Bachchan
364,India,21500000.0,421100.0,alexandra daddario
365,India,31500000.0,286900.0,Lamborghini
366,India,34700000.0,259600.0,Parineeti Chopra
381,India,11800000.0,725400.0,Lea Elui G
393,India,26100000.0,320200.0,FAISAL SHAIKH
407,India,10900000.0,729400.0,Anupama Parameswaran
415,India,9900000.0,794300.0,Dulquer Salmaan
426,India,26900000.0,277900.0,Sayyed Arishfa Khan üíé
429,India,21800000.0,337700.0,mon
434,India,52300000.0,138700.0,Juventus
437,India,38400000.0,186700.0,Ranveer Singh
441,India,14100000.0,501800.0,Sonu Sood
442,India,13900000.0,505700.0,Ileana D'Cruz
456,India,11600000.0,591200.0,Keerthy Suresh
466,India,30700000.0,219900.0,Guru Randhawa
472,India,16200000.0,406900.0,HK
474,India,21200000.0,310600.0,Ananya üíõüí´
476,India,5700000.0,1200000.0,Yash
488,India,18400000.0,347200.0,Rakul Singh
499,India,14500000.0,433300.0,Darshan Raval #JannatVe
514,India,5600000.0,1100000.0,Ratan Tata
523,India,29500000.0,202400.0,Madhuri Dixit
543,India,23400000.0,241100.0,shreyaghoshal
544,India,11000000.0,510100.0,Angel Rai :)
560,India,14400000.0,364000.0,Paul Walker
565,India,6500000.0,817200.0,Austin McBroom
570,India,27200000.0,189800.0,apple
573,India,22800000.0,223200.0,Team India
575,India,13600000.0,375600.0,Neha Sharma üí´
577,India,35100000.0,145400.0,Wiz Khalifa
592,India,15500000.0,314700.0,Tamannaah Bhatia
598,India,5200000.0,935000.0,Sai Pallavi
604,India,24200000.0,193300.0,Amanda ùïÆùñäùñóùñìùñû
606,India,7800000.0,605900.0,Mahesh Babu
618,India,16700000.0,269700.0,AB de Villiers
623,India,7800000.0,576700.0,Prabhas
628,India,9200000.0,485400.0,Genelia Deshmukh
632,India,10000000.0,440200.0,Dean Schneider
640,India,9100000.0,486800.0,djsnake
641,India,18600000.0,233000.0,Suresh Raina
647,India,10400000.0,416600.0,Anjali Arora
652,India,13300000.0,319400.0,Riteish Deshmukh
658,India,9400000.0,447100.0,jasprit bumrah
661,India,8500000.0,490600.0,David Warner
672,India,10300000.0,382000.0,Shikhar Dhawan
681,India,9900000.0,400100.0,Alex - that girl with the cars
704,India,6100000.0,638500.0,Tom Cruise
705,India,18400000.0,204400.0,Nidhhi Agerwal üåü
712,India,12000000.0,308600.0,Courteney Cox
714,India,12600000.0,291000.0,DILJIT DOSANJH
719,India,12500000.0,291200.0,√Ålvaro Morte
726,India,24200000.0,149800.0,Shilpa Shetty Kundra
745,India,9900000.0,359000.0,AishwaryaRaiBachchan
754,India,9500000.0,370700.0,Nita Shilimkar
772,India,12100000.0,277200.0,Kajol Devgan
782,India,31700000.0,102800.0,Sonam Kapoor Ahuja
783,India,13000000.0,249800.0,Yuvraj Singh
797,India,10000000.0,319500.0,Francia James
801,India,14700000.0,212500.0,Yami Gautam Dhar
813,India,5800000.0,542000.0,Joe Anoai aka ‚ÄúRoman Reigns‚Äù
820,India,11800000.0,256800.0,Jennifer Winget
823,India,10600000.0,284900.0,Mia Malkova
830,India,6900000.0,448600.0,Sidhu Moosewala (‡®Æ‡©Ç‡®∏‡©á ‡®Ü‡®≤‡®æ)
831,India,7500000.0,414300.0,Ivanka Trump
834,India,9000000.0,332400.0,ANNE-MARIE
845,India,6600000.0,448000.0,Esra BilgicÃß
896,India,10800000.0,252100.0,Bebe Rexha
898,India,11400000.0,239600.0,ARMAAN MALIK üßø
899,India,18800000.0,143800.0,Shruti Haasan
910,India,6000000.0,451800.0,‡§∂‡§ø‡§µ‡§æ‡§Ç‡§ó‡•Ä ‡§ú‡•ã‡§∂‡•Ä
930,India,5700000.0,457500.0,Nivetha Thomas
931,India,4000000.0,657600.0,Suriya Sivakumar
949,India,18500000.0,138400.0,Divyanka Tripathi Dahiya
973,India,4200000.0,596800.0,Ravindrasinh jadeja
986,India,5700000.0,433800.0,Rishabh Pant
997,India,10100000.0,239800.0,India‚Äôs Youth & Fitness IC‚≠ïÔ∏èN¬Æ
998,India,13700000.0,175500.0,Shakti Mohan

In [29]:
#the number is shown below
dt.shape

(143, 4)

# 2d.What percentage of influencers with average engagement less than 1.5 million were into Beauty and Lifestyle?

In [34]:
b_l=data[['Category','Engagement avg']]
b_l.shape

(1000, 2)

In [33]:
#numbinfluencers with Engagement avg less than 1.5 million that are in Beauty and lifestyle  
b_l1=b_l[(b_l['Engagement avg']<150000) & (b_l['Category']=='Beauty')]
b_l1

    Category  Engagement avg
695   Beauty         77000.0

In [36]:
#the percentage is printed out as shown bellow
percentage=1/1000*100
percentage

0.1

# 2e.What percentage of the influencers were into Sports with a ball, find out the difference between their average engagements and authentic engagements?

In [40]:
#The number of influencers who are into Sports with a ball
wh=data[(data['Category']=='Sports with a ball')]
wh

,Country,Rank,Account,Title,Link,Category,Followers,Audience Country,Authentic engagement,Engagement avg,Scraped
0,All,1,cristiano,Cristiano Ronaldo,https://www.instagram.com/cristiano/,Sports with a ball,400100000.0,India,7800000.0,9500000.0,2022-02-07 16:50:24.798803
10,All,11,neymarjr,NJ üáßüá∑,https://www.instagram.com/neymarjr/,Sports with a ball,169800000.0,Brazil,2800000.0,4000000.0,2022-02-07 16:50:24.798803
14,All,15,virat.kohli,Virat Kohli,https://www.instagram.com/virat.kohli/,Sports with a ball,182600000.0,India,2100000.0,2400000.0,2022-02-07 16:50:24.798803
38,All,39,kingjames,üëë,https://www.instagram.com/kingjames/,Sports with a ball,111400000.0,United States,884300.0,1500000.0,2022-02-07 16:50:24.798803
40,All,41,k.mbappe,Kylian MbappeÃÅ,https://www.instagram.com/k.mbappe/,Sports with a ball,65800000.0,France,1700000.0,2400000.0,2022-02-07 16:50:24.798803
53,All,54,fcbarcelona,FC Barcelona,https://www.instagram.com/fcbarcelona/,Sports with a ball,105100000.0,Indonesia,621000.0,950400.0,2022-02-07 16:50:24.798803
60,All,61,mosalah,Mohamed Salah,https://www.instagram.com/mosalah/,Sports with a ball,47900000.0,Egypt,1100000.0,1600000.0,2022-02-07 16:50:24.798803
79,All,80,paulpogba,Paul Labile Pogba,https://www.instagram.com/paulpogba/,Sports with a ball,51500000.0,Brazil,623400.0,1100000.0,2022-02-07 16:50:24.798803
83,All,84,realmadrid,Real Madrid C.F.,https://www.instagram.com/realmadrid/,Sports with a ball,109800000.0,Spain,364000.0,505000.0,2022-02-07 16:50:24.798803
101,All,102,paulodybala,Paulo Dybala,https://www.instagram.com/paulodybala/,Sports with a ball,45500000.0,Argentina,640200.0,1000000.0,2022-02-07 16:50:24.798803
107,All,108,iamzlatanibrahimovic,Zlatan Ibrahimoviƒá,https://www.instagram.com/iamzlatanibrahimovic/,Sports with a ball,52100000.0,Italy,525300.0,806100.0,2022-02-07 16:50:24.798803
108,All,109,karimbenzema,Karim Benzema,https://www.instagram.com/karimbenzema/,Sports with a ball,45200000.0,France,620700.0,895300.0,2022-02-07 16:50:24.798803
116,All,117,sergioramos,Sergio Ramos,https://www.instagram.com/sergioramos/,Sports with a ball,49400000.0,Spain,477400.0,731700.0,2022-02-07 16:50:24.798803
127,All,128,championsleague,UEFA Champions League,https://www.instagram.com/championsleague/,Sports with a ball,87900000.0,Brazil,277700.0,376000.0,2022-02-07 16:50:24.798803
132,All,133,hazardeden_10,Eden Hazard,https://www.instagram.com/hazardeden_10/,Sports with a ball,26900000.0,Spain,729500.0,1200000.0,2022-02-07 16:50:24.798803
137,All,138,kunaguero,Sergio Leonel AguÃàero,https://www.instagram.com/kunaguero/,Sports with a ball,21800000.0,Argentina,777700.0,1300000.0,2022-02-07 16:50:24.798803
144,All,145,jamesrodriguez10,James RodriÃÅguez,https://www.instagram.com/jamesrodriguez10/,Sports with a ball,48600000.0,Colombia,388400.0,591100.0,2022-02-07 16:50:24.798803
145,All,146,433,433,https://www.instagram.com/433/,Sports with a ball,46800000.0,Spain,366400.0,609700.0,2022-02-07 16:50:24.798803
147,All,148,phil.coutinho,Philippe Coutinho,https://www.instagram.com/phil.coutinho/,Sports with a ball,24100000.0,Brazil,704100.0,1100000.0,2022-02-07 16:50:24.798803
161,All,162,marcelotwelve,Marcelo Vieira,https://www.instagram.com/marcelotwelve/,Sports with a ball,51900000.0,Spain,308000.0,463000.0,2022-02-07 16:50:24.798803
163,All,164,manchesterunited,Manchester United,https://www.instagram.com/manchesterunited/,Sports with a ball,54700000.0,United Kingdom,270400.0,431000.0,2022-02-07 16:50:24.798803
172,All,173,garethbale11,Gareth Bale,https://www.instagram.com/garethbale11/,Sports with a ball,46000000.0,Spain,314300.0,492800.0,2022-02-07 16:50:24.798803
198,All,199,hardikpandya93,Hardik Himanshu Pandya,https://www.instagram.com/hardikpandya93/,Sports with a ball,20200000.0,India,771700.0,967600.0,2022-02-07 16:50:24.798803
208,All,209,m10_official,Mesut OÃàzil,https://www.instagram.com/m10_official/,Sports with a ball,24000000.0,Turkey,559800.0,786200.0,2022-02-07 16:50:24.798803
233,All,234,3gerardpique,Gerard PiqueÃÅ,https://www.instagram.com/3gerardpique/,Sports with a ball,19600000.0,Spain,561200.0,827600.0,2022-02-07 16:50:24.798803
241,All,242,vinijr,Vinicius Jr. ‚ö°Ô∏èüáßüá∑,https://www.instagram.com/vinijr/,Sports with a ball,14300000.0,Brazil,654400.0,1100000.0,2022-02-07 16:50:24.798803
245,All,246,luissuarez9,Luis Suarez,https://www.instagram.com/luissuarez9/,Sports with a ball,42900000.0,Brazil,241100.0,363000.0,2022-02-07 16:50:24.798803
256,All,257,_rl9,Robert Lewandowski,https://www.instagram.com/_rl9/,Sports with a ball,24200000.0,Poland,478300.0,607000.0,2022-02-07 16:50:24.798803
271,All,272,danialves,Dani Alves,https://www.instagram.com/danialves/,Sports with a ball,35000000.0,Brazil,253300.0,394400.0,2022-02-07 16:50:24.798803
285,All,286,psg,Paris Saint-Germain,https://www.instagram.com/psg/,Sports with a ball,56000000.0,Brazil,141100.0,236100.0,2022-02-07 16:50:24.798803
290,All,291,lukamodric10,Luka Modric,https://www.instagram.com/lukamodric10/,Sports with a ball,21000000.0,Spain,416900.0,611800.0,2022-02-07 16:50:24.798803
302,All,303,antogriezmann,Antoine Griezmann,https://www.instagram.com/antogriezmann/,Sports with a ball,35300000.0,Spain,210700.0,340300.0,2022-02-07 16:50:24.798803
309,All,310,zidane,zidane,https://www.instagram.com/zidane/,Sports with a ball,30700000.0,Spain,284400.0,387600.0,2022-02-07 16:50:24.798803
353,All,354,rahulkl,KL Rahulüëë,https://www.instagram.com/rahulkl/,Sports with a ball,11600000.0,India,707500.0,825000.0,2022-02-07 16:50:24.798803
356,All,357,houseofhighlights,House of Highlights,https://www.instagram.com/houseofhighlights/,Sports with a ball,31400000.0,United States,165200.0,303200.0,2022-02-07 16:50:24.798803
363,All,364,sanchooo10,Jadon Sancho,https://www.instagram.com/sanchooo10/,Sports with a ball,8100000.0,United Kingdom,654600.0,1100000.0,2022-02-07 16:50:24.798803
378,All,379,liverpoolfc,Liverpool Football Club,https://www.instagram.com/liverpoolfc/,Sports with a ball,35500000.0,United Kingdom,175600.0,245400.0,2022-02-07 16:50:24.798803
385,All,386,ronaldinho,Ronaldo de Assis Moreira,https://www.instagram.com/ronaldinho/,Sports with a ball,63300000.0,Brazil,76600.0,131800.0,2022-02-07 16:50:24.798803
402,All,403,easportsfifa,EA SPORTS FIFA,https://www.instagram.com/easportsfifa/,Sports with a ball,25500000.0,Spain,189100.0,316300.0,2022-02-07 16:50:24.798803
409,All,410,raphaelvarane,Raphael Varane,https://www.instagram.com/raphaelvarane/,Sports with a ball,18000000.0,Spain,294000.0,441600.0,2022-02-07 16:50:24.798803
413,All,414,marcusrashford,Marcus Rashford MBE,https://www.instagram.com/marcusrashford/,Sports with a ball,12600000.0,United Kingdom,393900.0,623300.0,2022-02-07 16:50:24.798803
424,All,425,achrafhakimi,Achraf Hakimi,https://www.instagram.com/achrafhakimi/,Sports with a ball,8000000.0,Morocco,639800.0,941800.0,2022-02-07 16:50:24.798803
434,All,435,juventus,Juventus,https://www.instagram.com/juventus/,Sports with a ball,52300000.0,India,97100.0,138700.0,2022-02-07 16:50:24.798803
471,All,472,alidaei,Ali Daei,https://www.instagram.com/alidaei/,Sports with a ball,7800000.0,Iran,523700.0,880200.0,2022-02-07 16:50:24.798803
493,All,494,chelseafc,Chelsea FC,https://www.instagram.com/chelseafc/,Sports with a ball,31800000.0,Indonesia,132200.0,197300.0,2022-02-07 16:50:24.798803
494,All,495,nba,NBA,https://www.instagram.com/nba/,Sports with a ball,63800000.0,United States,59100.0,98100.0,2022-02-07 16:50:24.798803
497,All,498,o.dembele7,Believe,https://www.instagram.com/o.dembele7/,Sports with a ball,9900000.0,Spain,375600.0,643800.0,2022-02-07 16:50:24.798803
502,All,503,frenkiedejong,Frenkie de Jong,https://www.instagram.com/frenkiedejong/,Sports with a ball,9600000.0,Spain,436900.0,655100.0,2022-02-07 16:50:24.798803
529,All,530,rogerfederer,Roger Federer,https://www.instagram.com/rogerfederer/,Sports with a ball,9100000.0,Spain,510400.0,661500.0,2022-02-07 16:50:24.798803
535,All,536,rafaelnadal,Rafa Nadal,https://www.instagram.com/rafaelnadal/,Sports with a ball,13500000.0,Spain,344000.0,431000.0,2022-02-07 16:50:24.798803
542,All,543,premierleague,Premier League,https://www.instagram.com/premierleague/,Sports with a ball,53700000.0,United Kingdom,73800.0,105300.0,2022-02-07 16:50:24.798803
550,All,551,kevindebruyne,Kevin De Bruyne,https://www.instagram.com/kevindebruyne/,Sports with a ball,16200000.0,United Kingdom,216600.0,335400.0,2022-02-07 16:50:24.798803
558,All,559,ansufati,Ansu Fati,https://www.instagram.com/ansufati/,Sports with a ball,7800000.0,Spain,455300.0,690600.0,2022-02-07 16:50:24.798803
563,All,564,iscoalarcon,Isco Alarcon Suarez,https://www.instagram.com/iscoalarcon/,Sports with a ball,22900000.0,Spain,159200.0,229800.0,2022-02-07 16:50:24.798803
569,All,570,obj,Odell Beckham Jr,https://www.instagram.com/obj/,Sports with a ball,15200000.0,United States,179300.0,342500.0,2022-02-07 16:50:24.798803
573,All,574,indiancricketteam,Team India,https://www.instagram.com/indiancricketteam/,Sports with a ball,22800000.0,India,191800.0,223200.0,2022-02-07 16:50:24.798803
583,All,584,fcbayern,FC Bayern,https://www.instagram.com/fcbayern/,Sports with a ball,30900000.0,Germany,109700.0,161500.0,2022-02-07 16:50:24.798803
591,All,592,aliiiiiiiikarimi8,Ali Karimi,https://www.instagram.com/aliiiiiiiikarimi8/,Sports with a ball,9000000.0,Iran,370200.0,557400.0,2022-02-07 16:50:24.798803
593,All,594,sadiomaneofficiel,Sadio Mane,https://www.instagram.com/sadiomaneofficiel/,Sports with a ball,9300000.0,United Kingdom,369000.0,525900.0,2022-02-07 16:50:24.798803
599,All,600,alishalehmann7,Alisha Lehmann,https://www.instagram.com/alishalehmann7/,Sports with a ball,6300000.0,Brazil,407300.0,768900.0,2022-02-07 16:50:24.798803
609,All,610,giannis_an34,Giannis Antetokounmpo,https://www.instagram.com/giannis_an34/,Sports with a ball,11900000.0,United States,244000.0,386100.0,2022-02-07 16:50:24.798803
622,All,623,melo,LaMelo Ball,https://www.instagram.com/melo/,Sports with a ball,8000000.0,United States,278700.0,567100.0,2022-02-07 16:50:24.798803
626,All,627,auba,Pierre-Emerick Aubameyang,https://www.instagram.com/auba/,Sports with a ball,10800000.0,United Kingdom,259800.0,414100.0,2022-02-07 16:50:24.798803
630,All,631,d_degeaofficial,David De Gea,https://www.instagram.com/d_degeaofficial/,Sports with a ball,12600000.0,United Kingdom,247100.0,349600.0,2022-02-07 16:50:24.798803
637,All,638,riyadmahrez26.7,RM26,https://www.instagram.com/riyadmahrez26.7/,Sports with a ball,8200000.0,Algeria,419200.0,539900.0,2022-02-07 16:50:24.798803
639,All,640,noahbeck,Noah Beck,https://www.instagram.com/noahbeck/,Sports with a ball,9000000.0,United States,298300.0,491500.0,2022-02-07 16:50:24.798803
661,All,662,davidwarner31,David Warner,https://www.instagram.com/davidwarner31/,Sports with a ball,8500000.0,India,417300.0,490600.0,2022-02-07 16:50:24.798803
666,All,667,thiagosilva,Thiago Silva,https://www.instagram.com/thiagosilva/,Sports with a ball,18600000.0,Brazil,128600.0,216300.0,2022-02-07 16:50:24.798803
667,All,668,toni.kr8s,Toni Kroos,https://www.instagram.com/toni.kr8s/,Sports with a ball,31200000.0,Germany,94400.0,128500.0,2022-02-07 16:50:24.798803
672,All,673,shikhardofficial,Shikhar Dhawan,https://www.instagram.com/shikhardofficial/,Sports with a ball,10300000.0,India,334000.0,382000.0,2022-02-07 16:50:24.798803
673,All,674,xavi,Xavi HernaÃÅndez,https://www.instagram.com/xavi/,Sports with a ball,7600000.0,Spain,353100.0,529800.0,2022-02-07 16:50:24.798803
683,All,684,memphisdepay,Memphis Depay,https://www.instagram.com/memphisdepay/,Sports with a ball,13500000.0,France,162700.0,288800.0,2022-02-07 16:50:24.798803
690,All,691,tombrady,Tom Brady,https://www.instagram.com/tombrady/,Sports with a ball,11300000.0,United States,186500.0,345300.0,2022-02-07 16:50:24.798803
697,All,698,kyrieirving,K.A.I H√©l√†,https://www.instagram.com/kyrieirving/,Sports with a ball,15900000.0,United States,159200.0,241200.0,2022-02-07 16:50:24.798803
701,All,702,marcoasensio10,Marco Asensio,https://www.instagram.com/marcoasensio10/,Sports with a ball,13300000.0,Spain,184900.0,283700.0,2022-02-07 16:50:24.798803
706,All,707,andresiniesta8,Andres Iniesta,https://www.instagram.com/andresiniesta8/,Sports with a ball,38800000.0,Spain,67000.0,96700.0,2022-02-07 16:50:24.798803
709,All,710,mterstegen1,Marc ter Stegen,https://www.instagram.com/mterstegen1/,Sports with a ball,13100000.0,Spain,189300.0,285200.0,2022-02-07 16:50:24.798803
718,All,719,angeldimariajm,AÃÅngel Di MariÃÅa,https://www.instagram.com/angeldimariajm/,Sports with a ball,15900000.0,Argentina,156400.0,230100.0,2022-02-07 16:50:24.798803
729,All,730,virgilvandijk,Virgil van Dijk,https://www.instagram.com/virgilvandijk/,Sports with a ball,11200000.0,United Kingdom,224800.0,319000.0,2022-02-07 16:50:24.798803
771,All,772,alexis_officia1,Sanchez Alexis,https://www.instagram.com/alexis_officia1/,Sports with a ball,13100000.0,Chile,156600.0,257900.0,2022-02-07 16:50:24.798803
778,All,779,roberto_firmino,ROBERTO FIRMINO,https://www.instagram.com/roberto_firmino/,Sports with a ball,13200000.0,Brazil,167700.0,249200.0,2022-02-07 16:50:24.798803
783,All,784,yuvisofficial,Yuvraj Singh,https://www.instagram.com/yuvisofficial/,Sports with a ball,13000000.0,India,209200.0,249800.0,2022-02-07 16:50:24.798803
790,All,791,marcinho11,Marco Reus,https://www.instagram.com/marcinho11/,Sports with a ball,10800000.0,Germany,217300.0,296500.0,2022-02-07 16:50:24.798803
815,All,816,stevengerrard,Steven Gerrard,https://www.instagram.com/stevengerrard/,Sports with a ball,9800000.0,United Kingdom,227500.0,318900.0,2022-02-07 16:50:24.798803
819,All,820,jesselingard,JLingz,https://www.instagram.com/jesselingard/,Sports with a ball,9300000.0,United Kingdom,215600.0,331200.0,2022-02-07 16:50:24.798803
838,All,839,davidalaba,David Alaba,https://www.instagram.com/davidalaba/,Sports with a ball,7900000.0,Spain,264900.0,375100.0,2022-02-07 16:50:24.798803
843,All,844,gabigol,Gabi üáßüá∑ Lil Gabi,https://www.instagram.com/gabigol/,Sports with a ball,9300000.0,Brazil,209700.0,317400.0,2022-02-07 16:50:24.798803
856,All,857,bleacherreport,Bleacher Report,https://www.instagram.com/bleacherreport/,Sports with a ball,17900000.0,United States,80300.0,158600.0,2022-02-07 16:50:24.798803
883,All,884,maradona,Diego Maradona,https://www.instagram.com/maradona/,Sports with a ball,7100000.0,Argentina,234600.0,395600.0,2022-02-07 16:50:24.798803
890,All,891,galatasaray,Galatasaray,https://www.instagram.com/galatasaray/,Sports with a ball,10800000.0,Turkey,208300.0,252800.0,2022-02-07 16:50:24.798803
915,All,916,antdavis23,Anthony Davis,https://www.instagram.com/antdavis23/,Sports with a ball,7100000.0,United States,245800.0,379000.0,2022-02-07 16:50:24.798803
919,All,920,perspolis,P e r s e p o l i s,https://www.instagram.com/perspolis/,Sports with a ball,7200000.0,Iran,261400.0,372600.0,2022-02-07 16:50:24.798803
929,All,930,kaka,KakaÃÅ,https://www.instagram.com/kaka/,Sports with a ball,17800000.0,Brazil,89800.0,145800.0,2022-02-07 16:50:24.798803
934,All,935,kingarturo23oficial,Arturo Vidal,https://www.instagram.com/kingarturo23oficial/,Sports with a ball,16500000.0,Italy,97500.0,156900.0,2022-02-07 16:50:24.798803
938,All,939,harrykane,Harry Kane,https://www.instagram.com/harrykane/,Sports with a ball,12100000.0,United Kingdom,154400.0,212800.0,2022-02-07 16:50:24.798803
943,All,944,dejesusoficial,Gabriel Jesus,https://www.instagram.com/dejesusoficial/,Sports with a ball,16300000.0,Brazil,101900.0,157300.0,2022-02-07 16:50:24.798803
955,All,956,romelulukaku,Romelu Lukaku,https://www.instagram.com/romelulukaku/,Sports with a ball,8600000.0,Italy,206500.0,297400.0,2022-02-07 16:50:24.798803
960,All,961,hziyech,Hakim Ziyech,https://www.instagram.com/hziyech/,Sports with a ball,5400000.0,Morocco,343400.0,469200.0,2022-02-07 16:50:24.798803
969,All,970,jordialbaoficial,Jordi Alba,https://www.instagram.com/jordialbaoficial/,Sports with a ball,13900000.0,Spain,124900.0,180500.0,2022-02-07 16:50:24.798803
972,All,973,davidluiz23,David Luiz,https://www.instagram.com/davidluiz23/,Sports with a ball,21000000.0,Brazil,53800.0,118900.0,2022-02-07 16:50:24.798803
983,All,984,casemiro,Casemiro,https://www.instagram.com/casemiro/,Sports with a ball,13600000.0,Spain,120400.0,180700.0,2022-02-07 16:50:24.798803
986,All,987,rishabpant,Rishabh Pant,https://www.instagram.com/rishabpant/,Sports with a ball,5700000.0,India,365300.0,433800.0,2022-02-07 16:50:24.798803
996,All,997,manuelneuer,Manuel Neuer,https://www.instagram.com/manuelneuer/,Sports with a ball,11500000.0,Germany,146500.0,210200.0,2022-02-07 16:50:24.798803

In [42]:
#the number is printed out below
wh.shape

(103, 11)

In [46]:
#Percentage of influencers who are into sports with a ball 
percentage1=103/1000*100
percentage1

10.299999999999999

In [49]:
wh1=wh[(wh['Category']=='Sports with a ball') & (wh['Engagement avg'])]
wh1.shape

(103, 11)

In [51]:
wh2=wh[(wh['Category']=='Sports with a ball') & (wh['Authentic engagement'])]
wh2.shape

(103, 11)

In [53]:
#There is no difference with regards to their number
whole=103-103
whole

0