# importing libraries

In [15]:
import pandas as pd
import numpy as np
import os as i
os.chdir(r'C:\Users\Public')

# Reading the dataset

In [16]:
gdata=pd.read_csv('inc.csv')

In [18]:
gdata.head()

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
0,Burkina Faso,2010,647.836096,3.779619,28.557390,20.515849,21.990434,86.051107,565.466002,1667.904627,low income,Sub Saharan Africa
1,Burkina Faso,2011,751.172770,6.738005,31.301753,26.195501,22.123512,82.982740,578.164337,1705.359774,low income,Sub Saharan Africa
2,Burkina Faso,2012,758.000427,5.823999,34.640523,26.598085,24.652993,83.389444,606.453327,1788.801284,low income,Sub Saharan Africa
3,Burkina Faso,2013,787.469438,-2.129171,36.958866,27.076985,23.709915,86.171965,622.075798,1834.881492,low income,Sub Saharan Africa
4,Burkina Faso,2014,792.846237,-0.620387,31.891558,26.932004,19.262249,85.697305,619.523667,1827.353699,low income,Sub Saharan Africa

In [73]:
gdata

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
0,Burkina Faso,2010,647.836096,3.779619,28.557390,20.515849,21.990434,86.051107,565.466002,1667.904627,low income,Sub Saharan Africa
1,Burkina Faso,2011,751.172770,6.738005,31.301753,26.195501,22.123512,82.982740,578.164337,1705.359774,low income,Sub Saharan Africa
2,Burkina Faso,2012,758.000427,5.823999,34.640523,26.598085,24.652993,83.389444,606.453327,1788.801284,low income,Sub Saharan Africa
3,Burkina Faso,2013,787.469438,-2.129171,36.958866,27.076985,23.709915,86.171965,622.075798,1834.881492,low income,Sub Saharan Africa
4,Burkina Faso,2014,792.846237,-0.620387,31.891558,26.932004,19.262249,85.697305,619.523667,1827.353699,low income,Sub Saharan Africa
...,...,...,...,...,...,...,...,...,...,...,...,...
825,Suriname,2015,9168.237157,4.854591,NaN,NaN,NaN,NaN,9144.263119,NaN,upper middle income,Lartin America & Caribbean
826,Suriname,2016,5872.789429,24.072295,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean
827,Suriname,2017,6295.560562,28.142276,NaN,NaN,NaN,NaN,NaN,16278.159560,upper middle income,Lartin America & Caribbean
828,Suriname,2018,6938.086981,5.662827,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean
829,Suriname,2019,6853.693411,4.422664,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean

In [20]:
gdata.tail()

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
825,Suriname,2015,9168.237157,4.854591,NaN,NaN,NaN,NaN,9144.263119,NaN,upper middle income,Lartin America & Caribbean
826,Suriname,2016,5872.789429,24.072295,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean
827,Suriname,2017,6295.560562,28.142276,NaN,NaN,NaN,NaN,NaN,16278.15956,upper middle income,Lartin America & Caribbean
828,Suriname,2018,6938.086981,5.662827,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean
829,Suriname,2019,6853.693411,4.422664,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean

In [19]:
poor=gdata[gdata.rpcgni<1027]

In [21]:
poor.head()

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
0,Burkina Faso,2010,647.836096,3.779619,28.557390,20.515849,21.990434,86.051107,565.466002,1667.904627,low income,Sub Saharan Africa
1,Burkina Faso,2011,751.172770,6.738005,31.301753,26.195501,22.123512,82.982740,578.164337,1705.359774,low income,Sub Saharan Africa
2,Burkina Faso,2012,758.000427,5.823999,34.640523,26.598085,24.652993,83.389444,606.453327,1788.801284,low income,Sub Saharan Africa
3,Burkina Faso,2013,787.469438,-2.129171,36.958866,27.076985,23.709915,86.171965,622.075798,1834.881492,low income,Sub Saharan Africa
4,Burkina Faso,2014,792.846237,-0.620387,31.891558,26.932004,19.262249,85.697305,619.523667,1827.353699,low income,Sub Saharan Africa

In [22]:
poor.tail()

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
383,Tanzania,2013,970.399601,9.666184,29.618411,19.012204,37.469953,73.136255,874.645718,2172.728288,lower middle income,Sub Saharan Africa
384,Tanzania,2014,1030.077648,6.050846,27.286813,18.069209,37.653967,71.563636,904.979968,2248.082321,lower middle income,Sub Saharan Africa
385,Tanzania,2015,947.933352,7.591364,23.652769,17.104911,32.758692,73.789165,929.922586,2310.042875,lower middle income,Sub Saharan Africa
386,Tanzania,2016,966.503017,7.472034,19.070495,16.349975,32.174786,70.545734,960.938761,2387.090895,lower middle income,Sub Saharan Africa
387,Tanzania,2017,1004.906588,2.703734,17.098663,15.140278,34.017162,67.941223,995.516346,2472.985897,lower middle income,Sub Saharan Africa

In [29]:
gdata.describe()

,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni
count,830.000000,815.000000,810.000000,730.000000,730.000000,713.000000,720.000000,698.000000,684.000000
mean,2014.500000,3962.935183,6.691034,40.289972,31.202669,23.836076,85.191394,3482.072069,7508.357712
std,2.874013,3620.382700,17.747937,20.003935,18.270572,9.533501,16.714379,3116.845161,6077.574195
min,2010.000000,228.213589,-30.199654,0.588271,0.611168,-0.098400,31.717296,279.115479,753.908944
25%,2012.000000,975.105672,1.557582,28.016034,19.040651,17.663228,77.230345,890.530007,2235.739145
50%,2014.500000,2880.798437,4.121846,35.508249,28.256907,22.104644,84.845779,2515.877199,5336.366254
75%,2017.000000,6218.013890,7.792608,50.179552,39.703089,28.142399,94.789381,5103.897714,11232.743707
max,2019.000000,21711.151590,440.829791,191.458232,158.374225,79.401080,153.600632,14076.425530,29342.254370

In [30]:
poor.describe()

,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni
count,185.000000,185.000000,185.000000,183.000000,183.000000,182.000000,183.000000,185.000000,180.000000
mean,2014.416216,658.128825,6.267208,37.096605,22.964285,23.802775,90.055454,620.218004,1656.585116
std,2.838929,204.608250,7.169992,13.079005,9.811843,9.189086,10.603843,163.229306,464.305235
min,2010.000000,228.213589,-8.480017,17.098663,5.732969,5.750756,51.572705,279.115479,753.908944
25%,2012.000000,512.595335,1.797312,28.986550,15.483471,18.385613,83.480010,499.074629,1257.725152
50%,2014.000000,665.948885,4.781000,33.999988,21.874381,22.750312,89.055159,619.523667,1744.696387
75%,2017.000000,781.433896,8.297993,39.928812,28.535356,28.468889,95.352389,725.728736,2001.961707
max,2019.000000,1516.404378,43.068660,82.467951,66.076120,53.987975,142.650071,1002.801858,2743.557061

In [40]:
rich=gdata[gdata.rpcgni>=4046]
rich

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
410,Botswana,2010,6434.812485,8.920002,51.264331,43.635464,38.053041,68.902742,5412.853279,12580.34149,upper middle income,Sub Saharan Africa
411,Botswana,2011,7617.310041,13.958077,53.595043,49.950535,35.453560,64.808996,5791.297629,13459.90702,upper middle income,Sub Saharan Africa
412,Botswana,2012,7050.573472,0.193794,61.404151,49.250744,38.082831,71.262036,6021.693014,13995.38295,upper middle income,Sub Saharan Africa
413,Botswana,2013,7224.912737,2.309145,61.030942,61.522640,29.409076,70.569981,6457.156215,15007.46945,upper middle income,Sub Saharan Africa
414,Botswana,2014,7495.220866,7.799174,57.528228,60.560299,24.955344,72.270915,6948.045149,16148.37428,upper middle income,Sub Saharan Africa
...,...,...,...,...,...,...,...,...,...,...,...,...
798,Peru,2018,6957.793411,2.267261,23.441657,25.194733,21.363228,76.883696,6240.347862,12142.66015,upper middle income,Lartin America & Caribbean
799,Peru,2019,7027.612207,1.984871,22.893311,23.895965,21.043941,77.953404,6323.103560,12303.68873,upper middle income,Lartin America & Caribbean
805,St. Lucia,2015,10093.618020,4.437675,NaN,NaN,NaN,NaN,9239.865838,NaN,upper middle income,Lartin America & Caribbean
815,St. Vincent and the Grenadines,2015,6921.702479,2.440450,NaN,NaN,NaN,NaN,6754.757020,NaN,upper middle income,Lartin America & Caribbean
825,Suriname,2015,9168.237157,4.854591,NaN,NaN,NaN,NaN,9144.263119,NaN,upper middle income,Lartin America & Caribbean

In [36]:
rich.head()

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
410,Botswana,2010,6434.812485,8.920002,51.264331,43.635464,38.053041,68.902742,5412.853279,12580.34149,upper middle income,Sub Saharan Africa
411,Botswana,2011,7617.310041,13.958077,53.595043,49.950535,35.453560,64.808996,5791.297629,13459.90702,upper middle income,Sub Saharan Africa
412,Botswana,2012,7050.573472,0.193794,61.404151,49.250744,38.082831,71.262036,6021.693014,13995.38295,upper middle income,Sub Saharan Africa
413,Botswana,2013,7224.912737,2.309145,61.030942,61.522640,29.409076,70.569981,6457.156215,15007.46945,upper middle income,Sub Saharan Africa
414,Botswana,2014,7495.220866,7.799174,57.528228,60.560299,24.955344,72.270915,6948.045149,16148.37428,upper middle income,Sub Saharan Africa

In [45]:
gdata.describe

<bound method NDFrame.describe of           country  year        pcgdp  inflation     import     export  \
0    Burkina Faso  2010   647.836096   3.779619  28.557390  20.515849
1    Burkina Faso  2011   751.172770   6.738005  31.301753  26.195501
2    Burkina Faso  2012   758.000427   5.823999  34.640523  26.598085
3    Burkina Faso  2013   787.469438  -2.129171  36.958866  27.076985
4    Burkina Faso  2014   792.846237  -0.620387  31.891558  26.932004
..            ...   ...          ...        ...        ...        ...
825      Suriname  2015  9168.237157   4.854591        NaN        NaN
826      Suriname  2016  5872.789429  24.072295        NaN        NaN
827      Suriname  2017  6295.560562  28.142276        NaN        NaN
828      Suriname  2018  6938.086981   5.662827        NaN        NaN
829      Suriname  2019  6853.693411   4.422664        NaN        NaN

       capital  consumption       rpcgni        pppgni               incgrp  \
0    21.990434    86.051107   565.466002   1667.904627           low income
1    22.123512    82.982740   578.164337   1705.359774           low income
2    24.652993    83.389444   606.453327   1788.801284           low income
3    23.709915    86.171965   622.075798   1834.881492           low income
4    19.262249    85.697305   619.523667   1827.353699           low income
..         ...          ...          ...           ...                  ...
825        NaN          NaN  9144.263119           NaN  upper middle income
826        NaN          NaN          NaN           NaN  upper middle income
827        NaN          NaN          NaN  16278.159560  upper middle income
828        NaN          NaN          NaN           NaN  upper middle income
829        NaN          NaN          NaN           NaN  upper middle income

                         region
0            Sub Saharan Africa
1            Sub Saharan Africa
2            Sub Saharan Africa
3            Sub Saharan Africa
4            Sub Saharan Africa
..                          ...
825  Lartin America & Caribbean
826  Lartin America & Caribbean
827  Lartin America & Caribbean
828  Lartin America & Caribbean
829  Lartin America & Caribbean

[830 rows x 12 columns]>

In [37]:
rich.tail()

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
798,Peru,2018,6957.793411,2.267261,23.441657,25.194733,21.363228,76.883696,6240.347862,12142.66015,upper middle income,Lartin America & Caribbean
799,Peru,2019,7027.612207,1.984871,22.893311,23.895965,21.043941,77.953404,6323.103560,12303.68873,upper middle income,Lartin America & Caribbean
805,St. Lucia,2015,10093.618020,4.437675,NaN,NaN,NaN,NaN,9239.865838,NaN,upper middle income,Lartin America & Caribbean
815,St. Vincent and the Grenadines,2015,6921.702479,2.440450,NaN,NaN,NaN,NaN,6754.757020,NaN,upper middle income,Lartin America & Caribbean
825,Suriname,2015,9168.237157,4.854591,NaN,NaN,NaN,NaN,9144.263119,NaN,upper middle income,Lartin America & Caribbean

In [43]:
middle=gdata[(gdata['rpcgni']>1026) & (gdata['rpcgni']<4046)]
middle

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
192,South Sudan,2012,1179.739711,46.506905,28.787759,42.832052,7.074253,78.846103,1112.535580,NaN,low income,Sub Saharan Africa
193,South Sudan,2013,1779.470365,36.512159,41.070489,9.740758,11.367774,119.912389,1236.216166,NaN,low income,Sub Saharan Africa
194,South Sudan,2014,1322.820364,-26.700285,26.242901,38.391617,7.994509,79.856774,1060.136291,NaN,low income,Sub Saharan Africa
200,Sudan,2010,1338.443724,22.669419,23.304571,20.354426,25.258055,77.691898,1243.989068,4337.199423,low income,Sub Saharan Africa
201,Sudan,2011,1366.410905,26.328350,13.846957,15.741213,21.688372,76.417524,1323.525591,4614.505527,low income,Sub Saharan Africa
...,...,...,...,...,...,...,...,...,...,...,...,...
733,Guatemala,2013,3522.773706,3.358446,34.687065,21.998155,15.842627,96.846283,3714.893493,7557.667802,upper middle income,Lartin America & Caribbean
734,Guatemala,2014,3779.642336,2.860312,33.338916,21.744363,15.071162,96.523391,3801.957747,7734.793394,upper middle income,Lartin America & Caribbean
735,Guatemala,2015,3994.636913,2.231621,30.063546,19.829908,14.828155,95.405483,3899.155248,7932.534306,upper middle income,Lartin America & Caribbean
736,Guatemala,2016,4173.301666,2.707191,27.619648,18.753089,13.861969,95.004590,3946.502604,8028.858895,upper middle income,Lartin America & Caribbean
737,Guatemala,2017,4454.048150,1.747914,27.574374,18.495046,13.596106,95.483221,4005.002111,8147.871684,upper middle income,Lartin America & Caribbean

In [56]:
rich1=gdata[(gdata['rpcgni']>=4046) & (gdata['region']=='Sub Saharan Africa')]
rich1

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
410,Botswana,2010,6434.812485,8.920002,51.264331,43.635464,38.053041,68.902742,5412.853279,12580.341490,upper middle income,Sub Saharan Africa
411,Botswana,2011,7617.310041,13.958077,53.595043,49.950535,35.453560,64.808996,5791.297629,13459.907020,upper middle income,Sub Saharan Africa
412,Botswana,2012,7050.573472,0.193794,61.404151,49.250744,38.082831,71.262036,6021.693014,13995.382950,upper middle income,Sub Saharan Africa
413,Botswana,2013,7224.912737,2.309145,61.030942,61.522640,29.409076,70.569981,6457.156215,15007.469450,upper middle income,Sub Saharan Africa
414,Botswana,2014,7495.220866,7.799174,57.528228,60.560299,24.955344,72.270915,6948.045149,16148.374280,upper middle income,Sub Saharan Africa
415,Botswana,2015,6402.910183,3.816146,59.598500,52.903172,29.074111,77.843480,6530.494288,15177.918930,upper middle income,Sub Saharan Africa
416,Botswana,2016,6982.917492,11.683724,45.853318,54.611351,22.067691,69.174276,6822.483801,15856.549510,upper middle income,Sub Saharan Africa
417,Botswana,2017,7296.092142,-2.647418,39.044533,42.964736,23.830520,70.852418,6946.541806,16144.880270,upper middle income,Sub Saharan Africa
418,Botswana,2018,7503.878588,-0.331891,43.527645,44.535787,27.318254,72.219727,7007.129719,16285.696320,upper middle income,Sub Saharan Africa
419,Botswana,2019,7203.064221,0.445651,46.371478,37.383152,29.833248,75.801040,7016.764020,16308.087990,upper middle income,Sub Saharan Africa
420,Equatorial Guinea,2010,17288.842600,24.906534,58.909792,85.758433,38.056299,35.095059,7879.015553,19742.200780,upper middle income,Sub Saharan Africa
421,Equatorial Guinea,2011,21641.693900,17.045107,39.282034,75.095313,32.049271,32.137450,8128.050802,20366.200550,upper middle income,Sub Saharan Africa
422,Equatorial Guinea,2012,21711.151590,4.854782,44.770431,71.904992,41.148143,31.717296,8703.659137,21808.484200,upper middle income,Sub Saharan Africa
423,Equatorial Guinea,2013,20390.737270,-1.072674,39.239968,67.653317,30.308045,41.278606,8434.607589,21134.330220,upper middle income,Sub Saharan Africa
424,Equatorial Guinea,2014,19394.080660,-1.273843,38.415910,65.963289,28.709300,43.743321,8262.866770,20704.004670,upper middle income,Sub Saharan Africa
425,Equatorial Guinea,2015,11283.398050,-20.192750,42.219585,56.658474,24.701453,60.859659,8510.380333,21324.191600,upper middle income,Sub Saharan Africa
426,Equatorial Guinea,2016,9250.316493,-6.285422,41.187901,51.412830,16.698646,73.076418,7751.671937,19423.119890,upper middle income,Sub Saharan Africa
427,Equatorial Guinea,2017,9667.857801,12.742377,43.565153,58.863105,14.031717,70.670331,6626.681647,16604.267210,upper middle income,Sub Saharan Africa
428,Equatorial Guinea,2018,10005.616790,9.513843,44.031147,59.614534,12.501497,71.915115,6061.422409,15187.914960,upper middle income,Sub Saharan Africa
429,Equatorial Guinea,2019,8419.933336,-2.196443,41.698831,52.806925,7.710671,81.181231,5366.685947,13447.135720,upper middle income,Sub Saharan Africa
430,Gabon,2010,8849.322608,16.564320,31.494170,57.663492,29.701114,44.129564,5786.712366,12107.363420,upper middle income,Sub Saharan Africa
431,Gabon,2011,10809.684950,12.681228,28.754005,61.744372,26.642390,40.367244,5726.134584,11980.618360,upper middle income,Sub Saharan Africa
432,Gabon,2012,9813.505747,-2.941903,31.392467,60.950341,26.966150,43.475976,6219.715665,13013.323140,upper middle income,Sub Saharan Africa
433,Gabon,2013,9683.581620,-6.157925,33.277630,57.357406,29.180595,46.739629,6433.079571,13459.737990,upper middle income,Sub Saharan Africa
434,Gabon,2014,9663.424110,-0.851390,28.999437,44.520892,35.139049,49.339496,7007.682687,14661.962730,upper middle income,Sub Saharan Africa
435,Gabon,2015,7384.700704,-8.927172,27.917773,46.032009,29.230956,52.654808,6771.467149,14167.736100,upper middle income,Sub Saharan Africa
436,Gabon,2016,6984.419712,-4.269754,26.098034,44.035347,26.982261,55.080425,6772.767454,14170.456680,upper middle income,Sub Saharan Africa
437,Gabon,2017,7230.434912,3.820302,24.841986,50.226754,21.298608,53.201449,6719.112022,14058.195050,upper middle income,Sub Saharan Africa
438,Gabon,2018,7959.007267,7.176657,22.737521,54.299076,19.258232,49.180212,6385.369425,13359.915490,upper middle income,Sub Saharan Africa
439,Gabon,2019,7766.996554,1.547485,21.997016,51.431073,21.898797,48.667146,6242.930113,13061.894030,upper middle income,Sub Saharan Africa
440,Mauritius,2010,8000.376432,1.126419,62.219401,51.237673,27.105083,87.009225,7856.848785,16937.874070,upper middle income,Sub Saharan Africa
441,Mauritius,2011,9197.026972,3.161464,65.094799,52.444147,23.946686,86.849117,8091.350267,17443.414740,upper middle income,Sub Saharan Africa
442,Mauritius,2012,9291.227619,2.465524,65.707955,53.792165,24.380568,87.606518,8753.478613,18870.837720,upper middle income,Sub Saharan Africa
443,Mauritius,2013,9637.002650,2.750881,61.552322,48.417415,22.032132,88.855710,9333.025202,20120.230120,upper middle income,Sub Saharan Africa
444,Mauritius,2014,10153.938220,1.480635,59.292663,48.846101,19.675715,89.388158,9664.588104,20835.016780,upper middle income,Sub Saharan Africa
445,Mauritius,2015,9260.447303,0.960796,57.147353,47.862247,18.091063,89.637296,10045.983410,21657.232640,upper middle income,Sub Saharan Africa
446,Mauritius,2016,9681.618567,2.147570,53.735236,44.250342,17.900935,89.003485,10397.765430,22415.607860,upper middle income,Sub Saharan Africa
447,Mauritius,2017,10484.908360,1.296872,54.913703,42.451788,18.275113,89.996085,10917.588550,23536.247810,upper middle income,Sub Saharan Africa
448,Mauritius,2018,11208.343820,1.447272,54.020729,40.963437,19.404849,91.048839,11488.921660,24767.933510,upper middle income,Sub Saharan Africa
449,Mauritius,2019,11097.168980,0.504436,53.669012,38.470338,19.799139,91.194451,11869.943230,25589.343660,upper middle income,Sub Saharan Africa
451,Namibia,2011,5806.748246,3.814876,56.649366,45.539782,22.054009,87.619060,4111.836258,8965.820525,upper middle income,Sub Saharan Africa
452,Namibia,2012,5942.292740,11.260308,60.155071,40.058338,26.722669,93.373135,4250.763567,9268.750223,upper middle income,Sub Saharan Africa
453,Namibia,2013,5392.094938,4.039791,60.222919,37.501985,29.395419,93.325275,4576.548698,9979.121655,upper middle income,Sub Saharan Africa
454,Namibia,2014,5469.901400,8.234892,64.063052,39.017085,34.776552,90.269245,4754.976848,10368.182570,upper middle income,Sub Saharan Africa
455,Namibia,2015,4896.615260,3.864574,61.868183,35.370848,30.556440,95.940723,4888.791824,10659.964870,upper middle income,Sub Saharan Africa
456,Namibia,2016,4546.986688,7.968672,58.956721,35.009467,22.029944,101.917135,4710.171611,10270.485170,upper middle income,Sub Saharan Africa
457,Namibia,2017,5367.114674,9.919038,47.598863,33.620805,17.766496,96.211235,4580.215747,9987.117622,upper middle income,Sub Saharan Africa
458,Namibia,2018,5588.392864,4.428485,45.831302,35.882565,14.916348,95.032095,4450.484622,9704.240117,upper middle income,Sub Saharan Africa
459,Namibia,2019,5009.685904,0.612682,47.034596,36.440267,15.192289,95.401817,4386.953166,9565.710371,upper middle income,Sub Saharan Africa
460,South Africa,2010,8148.961202,6.128432,24.622670,25.783418,17.595645,80.363553,5964.677026,13354.961250,upper middle income,Sub Saharan Africa
461,South Africa,2011,8810.930651,5.539056,26.938202,27.698148,18.853238,81.127919,6035.843514,13514.303610,upper middle income,Sub Saharan Africa
462,South Africa,2012,8222.197279,4.685206,28.443468,27.139149,18.584535,83.122072,6075.124258,13602.253520,upper middle income,Sub Saharan Africa
463,South Africa,2013,7467.079185,5.844111,30.495747,28.379280,19.168763,82.947708,6133.185230,13732.252520,upper middle income,Sub Saharan Africa
464,South Africa,2014,6988.808739,5.366546,30.498955,29.000619,18.487964,83.010373,6119.153143,13700.834560,upper middle income,Sub Saharan Africa
465,South Africa,2015,6259.839681,5.545528,29.013038,27.713638,18.633207,82.666195,6116.425843,13694.728110,upper middle income,Sub Saharan Africa
466,South Africa,2016,5756.965741,6.952172,27.705169,28.156088,16.960452,82.588631,6049.713484,13545.358590,upper middle income,Sub Saharan Africa
467,South Africa,2017,6690.939847,5.473322,26.195856,27.340076,16.610734,82.245048,6018.730851,13475.988210,upper middle income,Sub Saharan Africa
468,South Africa,2018,7005.095413,3.956474,27.018995,27.488588,16.540896,82.989511,6025.534566,13491.221790,upper middle income,Sub Saharan Africa
469,South Africa,2019,6624.761865,4.499449,26.808066,27.342180,16.021141,83.420876,5969.819206,13366.474640,upper middle income,Sub Saharan Africa

In [61]:
inc_cat=['upper middle income']
gdata[gdata.incgrp.isin(inc_cat)]

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
410,Botswana,2010,6434.812485,8.920002,51.264331,43.635464,38.053041,68.902742,5412.853279,12580.34149,upper middle income,Sub Saharan Africa
411,Botswana,2011,7617.310041,13.958077,53.595043,49.950535,35.453560,64.808996,5791.297629,13459.90702,upper middle income,Sub Saharan Africa
412,Botswana,2012,7050.573472,0.193794,61.404151,49.250744,38.082831,71.262036,6021.693014,13995.38295,upper middle income,Sub Saharan Africa
413,Botswana,2013,7224.912737,2.309145,61.030942,61.522640,29.409076,70.569981,6457.156215,15007.46945,upper middle income,Sub Saharan Africa
414,Botswana,2014,7495.220866,7.799174,57.528228,60.560299,24.955344,72.270915,6948.045149,16148.37428,upper middle income,Sub Saharan Africa
...,...,...,...,...,...,...,...,...,...,...,...,...
825,Suriname,2015,9168.237157,4.854591,NaN,NaN,NaN,NaN,9144.263119,NaN,upper middle income,Lartin America & Caribbean
826,Suriname,2016,5872.789429,24.072295,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean
827,Suriname,2017,6295.560562,28.142276,NaN,NaN,NaN,NaN,NaN,16278.15956,upper middle income,Lartin America & Caribbean
828,Suriname,2018,6938.086981,5.662827,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean
829,Suriname,2019,6853.693411,4.422664,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean

In [72]:
gcountry = gdata[~gdata.country.str.contains('Gh')]
gcountry

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
0,Burkina Faso,2010,647.836096,3.779619,28.557390,20.515849,21.990434,86.051107,565.466002,1667.904627,low income,Sub Saharan Africa
1,Burkina Faso,2011,751.172770,6.738005,31.301753,26.195501,22.123512,82.982740,578.164337,1705.359774,low income,Sub Saharan Africa
2,Burkina Faso,2012,758.000427,5.823999,34.640523,26.598085,24.652993,83.389444,606.453327,1788.801284,low income,Sub Saharan Africa
3,Burkina Faso,2013,787.469438,-2.129171,36.958866,27.076985,23.709915,86.171965,622.075798,1834.881492,low income,Sub Saharan Africa
4,Burkina Faso,2014,792.846237,-0.620387,31.891558,26.932004,19.262249,85.697305,619.523667,1827.353699,low income,Sub Saharan Africa
...,...,...,...,...,...,...,...,...,...,...,...,...
825,Suriname,2015,9168.237157,4.854591,NaN,NaN,NaN,NaN,9144.263119,NaN,upper middle income,Lartin America & Caribbean
826,Suriname,2016,5872.789429,24.072295,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean
827,Suriname,2017,6295.560562,28.142276,NaN,NaN,NaN,NaN,NaN,16278.159560,upper middle income,Lartin America & Caribbean
828,Suriname,2018,6938.086981,5.662827,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean
829,Suriname,2019,6853.693411,4.422664,NaN,NaN,NaN,NaN,NaN,NaN,upper middle income,Lartin America & Caribbean

In [79]:
gdata.query('incgrp=="low income" and capital>50')

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
86,Guinea,2016,732.291512,5.668954,82.467951,29.371511,52.669842,100.426597,815.893988,2213.959111,low income,Sub Saharan Africa
143,Mozambique,2013,664.077510,2.976380,76.406568,26.743936,53.987975,95.674658,542.806625,1163.397474,low income,Sub Saharan Africa
144,Mozambique,2014,673.969212,1.210685,80.181135,31.284040,52.855124,96.041972,562.361830,1205.310147,low income,Sub Saharan Africa
148,Mozambique,2018,503.317925,3.001170,82.334154,44.870003,50.047823,87.416328,590.591981,1265.815831,low income,Sub Saharan Africa

In [85]:
gdata.nlargest(10,'inflation')

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
409,Zimbabwe,2019,1316.740657,440.829791,32.030875,31.251040,7.408702,93.371133,NaN,NaN,lower middle income,Sub Saharan Africa
127,Malawi,2017,506.137294,60.986971,NaN,NaN,NaN,NaN,NaN,1439.504186,low income,Sub Saharan Africa
408,Zimbabwe,2018,1254.642265,59.803356,41.397264,28.049757,9.687734,103.659773,1506.475999,3864.012419,lower middle income,Sub Saharan Africa
208,Sudan,2018,740.746767,55.975325,0.683885,0.611168,36.710064,63.362670,1178.713355,4109.613994,low income,Sub Saharan Africa
313,Ghana,2013,2361.090324,54.012912,35.318539,25.440783,24.771806,85.105949,1715.607468,4623.712983,lower middle income,Sub Saharan Africa
209,Sudan,2019,610.927862,51.978893,0.588271,0.630574,35.804239,64.153447,1121.420309,3909.860336,low income,Sub Saharan Africa
649,Argentina,2019,10056.637940,50.921499,14.518503,17.695944,15.057766,81.936276,12198.467050,21197.741040,upper middle income,Lartin America & Caribbean
192,South Sudan,2012,1179.739711,46.506905,28.787759,42.832052,7.074253,78.846103,1112.535580,NaN,low income,Sub Saharan Africa
47,"Congo, Dem. Rep.",2017,467.074232,43.068660,34.393039,30.690155,24.987678,78.715206,482.857445,1029.883308,low income,Sub Saharan Africa
648,Argentina,2018,11795.159390,42.033669,16.325850,14.436686,16.613885,85.275279,12616.821310,21924.731190,upper middle income,Lartin America & Caribbean

In [86]:
gdata.nsmallest(10,'inflation')

,country,year,pcgdp,inflation,import,export,capital,consumption,rpcgni,pppgni,incgrp,region
545,Iraq,2015,4688.318017,-30.199654,35.077622,34.514146,20.359652,74.345153,4645.694739,9859.834601,upper middle income,Middle East & North Africa
194,South Sudan,2014,1322.820364,-26.700285,26.242901,38.391617,7.994509,79.856774,1060.136291,NaN,low income,Sub Saharan Africa
425,Equatorial Guinea,2015,11283.398050,-20.192750,42.219585,56.658474,24.701453,60.859659,8510.380333,21324.191600,upper middle income,Sub Saharan Africa
575,Libya,2015,4337.919139,-19.398512,74.279261,39.966661,NaN,NaN,4523.040890,NaN,upper middle income,Middle East & North Africa
285,"Congo, Rep.",2015,2447.539308,-17.594712,79.965457,42.728167,79.401080,57.836210,2433.986667,5080.414310,lower middle income,Sub Saharan Africa
574,Libya,2014,6466.908237,-17.309029,91.883286,47.014327,NaN,NaN,NaN,NaN,upper middle income,Middle East & North Africa
50,Eritrea,2010,501.355317,-16.228200,31.093089,6.378377,12.385401,145.517039,NaN,NaN,low income,Sub Saharan Africa
344,Mauritania,2014,1677.109019,-11.876323,54.221171,37.389201,41.796720,75.035250,1429.847820,4722.797963,lower middle income,Sub Saharan Africa
546,Iraq,2016,4550.658638,-11.104171,26.479797,28.108524,17.877205,75.222272,5138.640957,10906.043720,upper middle income,Middle East & North Africa
435,Gabon,2015,7384.700704,-8.927172,27.917773,46.032009,29.230956,52.654808,6771.467149,14167.736100,upper middle income,Sub Saharan Africa

In [95]:
gdata.iloc[310:321,1:5]

     year        pcgdp  inflation     import
310  2010  1299.345212  16.595645  45.901098
311  2011  1549.462719  13.914822  49.358845
312  2012  1587.560932  15.205279  52.808817
313  2013  2361.090324  54.012912  35.318539
314  2014  2012.264247  23.939960  35.604660
315  2015  1774.074771  13.252965  42.689566
316  2016  1971.956935  15.748620  36.683761
317  2017  2074.290733  10.677311  36.671490
318  2018  2260.860567  10.568480  34.503622
319  2019  2246.625578   8.481073  39.375202
320  2010  1080.296184   1.639200  30.269928

In [98]:
from bs4 import BeautifulSoup
from urllib.request import urlopen

In [99]:
url='https://quotes.toscrape.com/'

In [104]:
html=urlopen(url)

In [107]:
soup=BeautifulSoup(html,'html.parser')
type(soup)

bs4.BeautifulSoup

In [137]:
all_links=soup.findAll('div',{'class':'quote'})

In [141]:
stri=str(all_links)

In [150]:
text_j=BeautifulSoup(stri, 'html.parser').get_text()

In [163]:
print(text_j)

[]